### ISSUE TITLE
Word wrap in firefox

### ISSUE THREAD

**Issue by warddr** [gnuradio/gr-website#6]
The text looks really bad in firefox, words are split at very strange places.
In chrome it looks much better.

Look at the picture for an example:

![capture](https://user-images.githubusercontent.com/4094814/50601939-11624380-0eb6-11e9-9a95-ba7f0af204d1.png)

**Comment by noc0lour** [comment]
Thanks for the report. The issue was fixed (in the now used) https://github.com/gnuradio/hugo-website repository
